{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-secrets.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::222073541442:role/BoundedKubernetesExternalSecrets_sboxapp
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"eks.amazonaws.com/role-arn":"arn:aws:iam::222073541442:role/BoundedKubernetesExternalSecrets_sboxapp"},"labels":{"app.kubernetes.io/instance":"external-secrets","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"external-secrets","helm.sh/chart":"external-secrets-0.7.2","sa-digital.cicd.parents":"external-secrets-sboxapp"},"name":"external-secrets","namespace":"external-secrets"}}

{{- end }}