{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-secrets.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::222073541442:role/BoundedKubernetesESOs_sboxapp
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
